services:
  edgeops-collector:
    build:
      context: .
      dockerfile: Dockerfile
    image: edgeops-collector:0.1.0
    container_name: edgeops-collector
    restart: unless-stopped
    env-file:
      - .env
    ports:
      - "8095:8095"
    group_add:
      - "${DOCKER_GID}"
    voluems:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config:ro
    networks:
      - smarthome

networks:
  smarthome:
    external: true
    name: ${SMARTHOME_NETWORK_NAME:-smarthome-stack_default}
